import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Me Deixe!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name='lang' content='pt-br' />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.top}>
        <div className={styles.logo}>
          &lt; <span className={styles.textLogo}>MD</span> /&gt;
        </div>
        <nav className={styles.menu}>
          <a href="http://">Principal</a>
          <a href="http://">Sobre</a>
          <a href="http://">Contato</a>
          <a href="http://">Amparar</a>
        </nav>
      </header>

      <main className={styles.main}>

        <section className={styles.hero}>
          <div>
            <h1 className={styles.titleHero}>Me deixe!</h1>
            <p className={styles.textHero}>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
            <div className={styles.actionButton}>
              <button className={styles.buttonHero}>Saiba mais</button>
            </div>
          </div>
          <div><img src="/12608.svg" alt="Tela do aplicativo Me Deixe" width={300} height={500} /></div>
        </section>

        <section className={styles.partnerships}>
          <h2>Instituições parceiras:</h2>
          <div className={styles.partnershipsImages}>
            <a href="#">
              <img src="/ufs_vertical_positiva.svg" alt='logo da UFS' />
            </a>
            <a href="#">
              <img src="/ifs_vertical_preto.png" alt='logo do IFS' />
            </a>
            <a href="#">
              <img src="/ssp_vertical_preto.png" alt='logo da SSP' />
            </a>
          </div>

        </section>

        <section className={styles.services}>
          <h2>Serviços de ajuda:</h2>
          <p>Conheça todos os canais de denúncia no estado de Sergipe.</p>
          <div className={styles.servicesBlocs}>
            <div className={styles.blocs}>
              <img src="/telephone.png" alt="telephone" className={styles.iconsServices} />
              <h4 className={styles.numberCall}>180 - Central de Atendimento à Mulher</h4>
            </div>

            <div className={styles.blocs}>
              <img src="/police.png" alt="icone carro de polícia" className={styles.iconsServices} />
              <h4 className={styles.numberCall}>
                190 - Polícia militar
              </h4>
            </div>

            <div className={styles.blocs}>
              <img src="/complaint.png" alt="icone de denúncia" className={styles.iconsServices} />
              <h4 className={styles.numberCall}>
                181 - Disque Denúncia
              </h4>
            </div>

            <div className={styles.blocs}>
              <img src="/precint.png" alt="icone de denúncia" className={styles.iconsServices} />
              <h4 className={styles.numberCall}>
                <a href="https://portalcidadao.ssp.se.gov.br/DelegaciaVirtual">
                  Delegacia virtual
                </a>
              </h4>
            </div>

            <div className={styles.blocs}>
              <img src="/woman-head.png" alt="icone de denúncia" className={styles.iconsServices} />
              <h4 className={styles.numberCall}>(79) 3205-3726 <br /> NUDEM - Núcleo Especializado de Promoção e Defesa de Direito da Mulher</h4>
            </div>

            <div className={styles.blocs}>Div 06</div>
            <div className={styles.blocs}>Div 07</div>
            <div className={styles.blocs}>Div 08</div>
            <div className={styles.blocs}>Div 09</div>
            <div className={styles.blocs}>Div 10</div>
            <div className={styles.blocs}>Div 11</div>
            <div className={styles.blocs}>Div 12</div>
          </div>

        </section>

        <section className={styles.womanRights}>

          <div className={styles.descriptionRights}>
            <h2>Os direitos da mulher garantidos pela <strong>Constituição federal de 1988</strong>:</h2>
            <p>Segundo a Constituição Federal de 1988, as mulheres têm uma série de direitos que estão estabelecidos sob a luz dos Direitos Humanos. Todos devem ser respeitados e garantidos pelo Estado.</p>
          </div>

          <div className={styles.rightsCarousel}>
            <div className="rights">
              <div className="imageRight"></div>
              <div className="rightDescription">
                <span className="title"></span>
                <span className="description"></span>
              </div>
            </div>
          </div>

        </section>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

    </div>
  )
}

export default Home
